name: AWS S3 Helper
description: Upload and download files from AWS S3

inputs:
  s3_bucket:
    description: S3 Bucket Name
    required: true
  local_file:
    description: Local file paths
    required: false
    default: ../artifacts/file_list.txt
  download_file:
    description: Download file paths
    required: false
    default: ''
  download_location:
    description: file download location
    required: false
    default: .
  mode:
    description: Mode of operation (upload/download)
    required: true
    default: single-upload

outputs:
  presigned_url:
    description: Pre-signed URL for the uploaded file
    value: ${{ steps.sync-data.outputs.presigned_url }}

runs:
  using: "composite"
  steps:
    - name: Sync Data
      id: sync-data
      shell: bash
      env:
        UPLOAD_LOCATION: ${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ github.workflow }}/${{ github.head_ref != '' && github.head_ref || github.run_id }}/
      run: |
        echo "::group::$(printf '__________ %-100s' 'Process' | tr ' ' _)"
        case "${{ inputs.mode }}" in
          multi-upload)
            echo "Uploading files to S3 bucket..."
            first_line=true
            # Start the JSON object
            echo "{" > ${{ github.workspace }}/presigned_urls.json
            while IFS= read -r file; do
              if [ -f "$file" ]; then
                echo "Uploading $file..."
                aws s3 cp "$file" s3://${{ inputs.s3_bucket }}/${{ env.UPLOAD_LOCATION }}
                echo "Uploaded $file to s3://${{ inputs.s3_bucket }}/${{ env.UPLOAD_LOCATION }}"
                echo "Creating Pre-signed URL for $file..."
                filename=$(basename "$file")
                presigned_url=$(aws s3 presign s3://${{ inputs.s3_bucket }}/${{ env.UPLOAD_LOCATION }}$filename --expires-in 259200)
                if [ "$first_line" = true ]; then
                  first_line=false
                else
                  echo "," >> ${{ github.workspace }}/presigned_urls.json
                fi
                # Append the pre-signed URL to the file
                echo " \"${file}\": \"${presigned_url}\"" >> ${{ github.workspace }}/presigned_urls.json
                echo "Pre-signed URL for $file: $presigned_url"
              else
                echo "Warning: $file does not exist or is not a regular file."
              fi
            done < "${{ inputs.local_file }}"
            # Close the JSON object
            echo "}" >> ${{ github.workspace }}/presigned_urls.json
            ;;
          single-upload)
            echo "Uploading single file to S3 bucket..."
            aws s3 cp "${{ inputs.local_file }}" s3://${{ inputs.s3_bucket }}/${{ env.UPLOAD_LOCATION }}
            echo "Uploaded ${{ inputs.local_file }} to s3://${{ inputs.s3_bucket }}/${{ env.UPLOAD_LOCATION }}"
            echo "Creating Pre-signed URL for ${{ inputs.local_file }}..."
            presigned_url=$(aws s3 presign s3://${{ inputs.s3_bucket }}/${{ env.UPLOAD_LOCATION }}${{ inputs.local_file }} --expires-in 259200)
            echo "presigned_url=${presigned_url}" >> "$GITHUB_OUTPUT"
            ;;
          download)
            #Download The required file from s3
            echo "Downloading files from S3 bucket..."
            aws s3 cp s3://${{ inputs.s3_bucket }}/${{ inputs.download_file }} ${{ inputs.download_location }}
            ;;
          *)
            echo "Invalid mode. Use 'upload' or 'download'."
            exit 1
            ;;
        esac

    - name: Upload artifacts
      if: ${{ inputs.mode == 'multi-upload' }}
      uses: actions/upload-artifact@v4
      with:
        name: presigned_urls.json
        path: ${{ github.workspace }}/presigned_urls.json
        retention-days: 3
