actions:
- deploy:
    timeout:
      minutes: 10
    to: downloads
    images:
      boot:
        headers:
          Authentication: Q_GITHUB_TOKEN
        url: "{{BUILD_DOWNLOAD_URL}}/{{BUILD_FILE_NAME}}"
    postprocess:
      docker:
        image: ghcr.io/foundriesio/lava-lmp-sign:main

- deploy:
    timeout:
      minutes: 15
    to: fastboot
    images:
      boot:
        url: downloads://{{BUILD_FILE_NAME}}

- command:
    name: pre_power_command
    timeout:
      minutes: 2

- command:
    name: network_turn_on
    timeout:
      minutes: 2

- boot:
    auto_login:
      login_prompt: 'login:'
      username: root
    prompts:
    - 'root@qcom-armv8a'
    timeout:
      minutes: 5
    method: fastboot

- command:
    name: pre_os_command
    timeout:
          minutes: 2

- test:
    timeout:
      minutes: 5
    definitions:
    - from: git
      name: "{{DEVICE_TYPE}}-smoke-test"
      path: automated/linux/smoke/smoke.yaml
      repository: https://github.com/linaro/test-definitions.git
      parameters:
        SKIP_INSTALL: "True"
        TESTS: "pwd, uname -a, ip a, dmesg" 

- command:
    name: network_turn_on

context:
  lava_test_results_dir: /home/lava-%s
  test_character_delay: 10

device_type: {{DEVICE_TYPE}}
job_name: boot test ({{DEVICE_TYPE}}) {{GITHUB_RUN_ID}}
context:
  test_character_delay: 10
metadata:
  build-commit: '{{GITHUB_SHA}}'
timeouts:
  job:
    minutes: 45
  action:
    minutes: 15
  connection:
    minutes: 2
priority: medium
visibility: public