paths:
  adsp: hexagon-dsp-binaries/qcm6490/Thundercomm/RB5/ADSP.HT.5.3.c2-00082-SM8250-1
  cdsp: hexagon-dsp-binaries/qcm6490/Thundercomm/RB5/CDSP.HT.2.3.c1-00076-SM8250-1
  firmware: linux-firmware/qcom/qcm6490
